# Generated by Django 4.0.4 on 2022-05-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0002_logindetails_delete_formcontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logindetails',
            old_name='numer',
            new_name='number',
        ),
    ]
