# Generated by Django 4.0.4 on 2022-05-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0003_rename_numer_logindetails_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='updatedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
            ],
        ),
    ]
