# Generated by Django 4.0.4 on 2022-05-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0004_updatedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatedetails',
            old_name='email',
            new_name='femail',
        ),
        migrations.RenameField(
            model_name='updatedetails',
            old_name='mobile',
            new_name='fmobile',
        ),
        migrations.RenameField(
            model_name='updatedetails',
            old_name='name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='updatedetails',
            old_name='password',
            new_name='fpassword',
        ),
    ]
