# Generated by Django 4.0.4 on 2022-05-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0005_rename_email_updatedetails_femail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatedetails',
            old_name='femail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='updatedetails',
            old_name='fmobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='updatedetails',
            old_name='fname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='updatedetails',
            old_name='fpassword',
            new_name='password',
        ),
    ]
