# Generated by Django 4.0.4 on 2022-05-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0006_rename_femail_updatedetails_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('lasst_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('publication_date', models.DateField()),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('website', models.CharField(max_length=60)),
                ('authors', models.ManyToManyField(to='my_app1.author')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=60)),
                ('state_province', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('website', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='updatedetails',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='my_app1.publisher'),
        ),
    ]
