# Generated by Django 4.0.4 on 2022-05-21 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0007_author_book_publisher_delete_updatedetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('pname', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
                ('rname', models.CharField(max_length=30)),
                ('delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=60)),
                ('pname', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=60)),
                ('card_num', models.CharField(max_length=30)),
                ('order_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=30)),
                ('Expiry_date', models.DateField()),
                ('review', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=60)),
                ('Customer_delivery', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='my_app1.customer_delivery')),
                ('Customer_orders', models.ManyToManyField(to='my_app1.customer_orders')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
