# Generated by Django 4.0.4 on 2022-05-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0008_customer_delivery_customer_orders_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logindetails',
            old_name='number',
            new_name='name',
        ),
    ]
