# Generated by Django 4.0.4 on 2022-05-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0009_rename_number_logindetails_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='signupdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
