# Generated by Django 4.0.4 on 2022-05-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0010_signupdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupdetails',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='signupdetails',
            old_name='password',
            new_name='password1',
        ),
    ]
