# Generated by Django 4.0.4 on 2022-05-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0011_rename_email_signupdetails_email1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupdetails',
            old_name='email1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='signupdetails',
            old_name='password1',
            new_name='password',
        ),
    ]
