# Generated by Django 4.0.4 on 2022-05-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0012_rename_email1_signupdetails_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='carddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
                ('pname', models.CharField(max_length=30)),
                ('pid', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('cardnum', models.CharField(max_length=30)),
                ('cardname', models.CharField(max_length=30)),
                ('edate', models.CharField(max_length=30)),
                ('cvv', models.CharField(max_length=30)),
            ],
        ),
    ]
