# Generated by Django 4.0.4 on 2022-06-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0014_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=30)),
            ],
        ),
    ]
